In [39]:
import pandas as pd

In [45]:
df = pd.read_pickle('../data/allCandidates.pkl')
df[['candidate_name', 'race', 'district']]

,candidate_name,race,district
candidate3451,Phil Fortunato,State Senator,Legislative District 31
candidate3450,Michelle Rylands,State Senator,Legislative District 31
candidate3452,Morgan Irwin,Representative Position 2,Legislative District 31
candidate3453,Nate Lowry,Representative Position 2,Legislative District 31
candidate3454,Rebecca Saldaña,State Senator,Legislative District 37
candidate3455,Manka Dhingra,State Senator,Legislative District 45
candidate3456,Jinyoung Lee Englund,State Senator,Legislative District 45
candidate3457,Patty Kuderer,State Senator,Legislative District 48
candidate3458,Michelle Darnell,State Senator,Legislative District 48
candidate3459,Vandana Slatter,Representative Position 1,Legislative District 48
candidate3460,Ciaran Dougherty,Representative Position 1,Legislative District 48